.catalog:
  name: "Autobots"
  version: "0.0.2"
  description: "Autobots environment"
  questions:
    - variable: DOMAIN
      label: "Domain"
      type: "string"
      required: true
      default: "localhost"
    - variable: ENV_VAR
      label: "Application environment variable"
      type: "enum"
      options:
        - production
        - development
      default: "production"
      required: true
