.catalog:
  name: "skins.cash"
  version: "0.0.1"
  description: "skins.cash environment"
  uuid: skinscash-0.0.1
  questions:
    - variable: DOMAIN
      label: "Domain"
      type: "string"
      required: true
      default: "localhost"
    - variable: ENV_VAR
      label: "Application environment variable"
      type: "enum"
      options:
        - production
        - development
      default: "production"
      required: true

