.catalog:
  name: "Wordpress sites"
  version: "1.0"
  description: "web sites"
  uuid:
  questions:
    - variable: DOMAIN
      label: "Domain"
      type: "string"
      required: true
      default: "localhost"
   - variable: MYSQL_HOST
      label: "DB Host"
      type: "string"
      required: true
      default: "MySQL-db-1"
   - variable: MYSQL_DB_NAME
      label: "Database name"
      type: "string"
      required: true
      default: "wp_localhost"
    - variable: MYSQL_DB_PASSWORD
      label: "Database password"
      type: "string"
      required: true
      default: "qwerty12"

web:
  retain_ip: true
  health_check:
    port: 80
    interval: 5000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 5000

