.catalog:
  name: "Autobots"
  version: "0.0.1"
  description: "Autobots environment"
  questions:
    - variable: DOMAIN
      label: "Domain"
      type: "string"
      required: true
      default: "localhost"
    - variable: TRAEFIK_ENGINE
      default: rancher
      label: "Treafik engine"
      required: true
      type: "enum"
      options:
        - rancher
        - docker
    - variable: RANCHER_URL
      label: "Rancher URL"
      type: "string"
      default: "http://rancher.gskins.net:8080"
    - variable: RANCHER_ACCESS_KEY
      label: "Rancher environment access key"
      type: "string"
    - variable: RANCHER_SECRET_KEY
      label: "Rancher environment secret key"
      type: "string"
    - variable: ENV_VAR
      label: "Application environment variable"
      type: "enum"
      options:
        - production
        - development
      default: "production"
      required: true
traefik:
  retain_ip: true
  health_check:
    port: 80
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET http://${DOMAIN}/ HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 5000