version: '2'
volumes:
  satis-data:
    external: true
    driver: 'null'
services:
  satis:
    image: globalgames/satis.ovm
    volumes:
    - satis-data:/var/www/repository
    ports:
    - 8888:3000
    - 5000:80
    labels:
      traefik.frontend.rule: Host:${TR_DOMAIN}
      traefik.port: ${TR_PORT}
      io.rancher.container.pull_image: always
