version: '2'
services:
  magento:
    image: globalgames/marketplace
    labels:
      traefik.port: 80
      traefik.enable: true
      traefik.frontend.rule: "Host:${DOMAIN}"
      io.rancher.container.pull_image: always
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento2
    volumes:
      - "mysql:/var/lib/mysql"

volumes:
  mysql:
